version: "3"
services:

  postgres-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: metabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - metabase-pgdata:/var/lib/postgresql/data

  metabase-app:
    image: metabase/metabase
    restart: always
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres-db
    depends_on:
      - postgres-db
    links:
      - postgres-db
